from __future__ import annotations

from dataclasses import dataclass

from fourth_combinator.discover import discover_job
from fourth_combinator.index import (
    JobIndex,
    ToolSlot,
    build_job_index,
    find_first_tool_block,
)
from fourth_combinator.parse import ParsedOrientation, ToolBlock, parse_orientation_file
from fourth_combinator.park import fmt_angle, park_and_rotate
from fourth_combinator.scrub import (
    extract_trailing_spindle_stop,
    scrub_inter_op_spindle_stops,
    scrub_orientation_hop,
)


@dataclass(frozen=True)
class PlanStep:
    tool_number: int
    occurrence: int
    angle: float
    source_file: str


def build_execution_plan(index: JobIndex) -> tuple[PlanStep, ...]:
    """Build T×A steps from the union tool order.

    Final-tools / run-last logic:
    - Orientations in ``final_exclude_angles`` keep each final tool in its
      natural sequence position (e.g. T2 first on A0 when A0 is excluded).
    - All other orientations for those tools are deferred to last passes,
      in ``final_tools`` list order.
    """
    angles = tuple(item.angle for item in index.discovery.orientations)
    final_set = index.final_tool_set
    keep_natural = index.final_exclude_angles
    steps: list[PlanStep] = []

    def append_step(tool_number: int, occurrence: int, angle: float) -> None:
        orientation = index.by_angle[angle]
        block = find_first_tool_block(orientation, tool_number=tool_number)
        if block is None:
            return
        steps.append(
            PlanStep(
                tool_number=tool_number,
                occurrence=occurrence,
                angle=angle,
                source_file=orientation.path.name,
            )
        )

    for slot in index.tool_sequence:
        for angle in angles:
            if slot.tool_number in final_set and angle not in keep_natural:
                continue
            append_step(slot.tool_number, slot.occurrence, angle)

    # Deferred passes: one pass per final tool, in list order.
    for tool_number in index.final_tools:
        for angle in angles:
            if angle in keep_natural:
                continue
            append_step(tool_number, 0, angle)

    return tuple(steps)


def _tool_change_block(index: JobIndex, step: PlanStep) -> ToolBlock:
    """Prefer A0/reference setup for a tool change; else first orientation that has it."""
    ref = index.by_angle[index.reference_angle]
    ref_block = find_first_tool_block(ref, tool_number=step.tool_number)
    if ref_block is not None:
        return ref_block

    for item in index.discovery.orientations:
        block = find_first_tool_block(
            index.by_angle[item.angle],
            tool_number=step.tool_number,
        )
        if block is not None:
            return block
    raise ValueError(f"Internal error: no tool-change source for T{step.tool_number}")


def _block_for_step(
    index: JobIndex,
    step: PlanStep,
    *,
    prev_tool: int | None,
    first_step: bool,
) -> ToolBlock:
    orientation = index.by_angle[step.angle]
    block = find_first_tool_block(orientation, tool_number=step.tool_number)
    if block is None:
        raise ValueError(
            f"Internal error: missing T{step.tool_number} at A{step.angle}"
        )

    if first_step:
        prepared = block
    elif prev_tool is not None and step.tool_number != prev_tool:
        prepared = _tool_change_block(index, step)
    else:
        prepared = scrub_orientation_hop(block)

    # Same tool, same A: drop MOS stop→restart bridges between Fusion ops.
    return scrub_inter_op_spindle_stops(prepared)


def combine_job(index: JobIndex, *, verbose: bool = False) -> str:
    ref = index.by_angle[index.reference_angle]
    steps = build_execution_plan(index)

    out: list[str] = []
    out.append("; Generated by fourth_combinator — multi-orientation A-axis combiner")
    out.append(f"; Model: {index.discovery.model}")
    out.append("")

    if ref.preamble:
        out.extend(ref.preamble)
        out.append("")

    prev_angle: float | None = None
    prev_tool: int | None = None

    for step_idx, step in enumerate(steps):
        orientation = index.by_angle[step.angle]
        is_last = step_idx == len(steps) - 1
        source_block = find_first_tool_block(
            orientation,
            tool_number=step.tool_number,
        )

        out.append(
            f"; === T{step.tool_number} @ A{fmt_angle(step.angle)} "
            f"({orientation.path.name}) ==="
        )

        if prev_angle is not None and step.angle != prev_angle:
            out.extend(park_and_rotate(step.angle))

        block = _block_for_step(
            index,
            step,
            prev_tool=prev_tool,
            first_step=step_idx == 0,
        )
        if (
            verbose
            and source_block is not None
            and block != source_block
            and step_idx > 0
            and prev_tool == step.tool_number
        ):
            out.append("; (scrubbed spindle bookends)")

        if not is_last:
            block, _ = extract_trailing_spindle_stop(block)

        if block.lines:
            out.extend(block.lines)

        prev_angle = step.angle
        prev_tool = step.tool_number

    out.append("")
    return "\n".join(out).rstrip() + "\n"


def load_and_combine(
    job_dir,
    *,
    required_angles: tuple[float, ...] | None = None,
    strict: bool = False,
    verbose: bool = False,
    final_tools: tuple[int, ...] = (),
    final_exclude_angles: frozenset[float] | None = None,
) -> tuple[str, JobIndex, tuple[str, ...]]:
    from pathlib import Path

    discovery = discover_job(Path(job_dir), required_angles=required_angles)
    parsed: dict[float, ParsedOrientation] = {}
    for item in discovery.orientations:
        parsed[item.angle] = parse_orientation_file(item.path, angle=item.angle)

    index = build_job_index(
        discovery,
        parsed,
        strict=strict,
        final_tools=final_tools,
        final_exclude_angles=final_exclude_angles,
    )
    gcode = combine_job(index, verbose=verbose)
    return gcode, index, discovery.warnings
